### PR TITLE
[compilers] Add cross-compile section with two initial entries

### PR DESCRIPTION
**Pull request by weliveindetail**
Hi Matt, I didn't find resources on cross-compilation yet, so I am adding a new section in [compilers] here with two links that have been quite relevant for me. What do you think?

### CODE REVIEW

**Comment by MattPD** [comment]
Hi! I think the section makes sense.
Suggested minor changes:
- Make sure to insert the section between "Courses" and "Implementations" to maintain alphabetical order
- Formatting: Follow the existing formatting, e.g., under 2018 talks cf. "Introduction to LLVM: Building simple program analysis tools and instrumentation"

**Comment by weliveindetail** [comment]
Thanks for the notes. Sure, like so?

**Comment by MattPD** [comment]
Just change the FOSDEM talk link to https://archive.fosdem.org/2018/schedule/event/crosscompile/ (this includes both the recording as well as the slides) and it should be good to go!

**Comment by MattPD** [comment]
Merged; thanks!

**Pull request merged**
