### PR TITLE
Add MLIR entry

### PR DESCRIPTION
**Pull request by xgupta**

### CODE REVIEW

**Comment by MattPD** [comment]
Thanks! MLIR is a better fit for intermediate representations section under program analysis or compilers, but that's currently under construction. It _would_ be a better fit here (among compilers for C++) if Clang IL (CIL) discussed, e.g., in https://llvm.org/devmtg/2019-04/slides/Keynote-ShpeismanLattner-MLIR.pdf, were to ever materialize as an MLIR dialect (similarly to Flang using its MLIR dialect, FIR, https://mlir.llvm.org/users/) . Closing for now, but feel free to reopen if Clang uses MLIR some day! :-)

**Comment by xgupta** [comment]
> It _would_ be a better fit here (among compilers for C++) if Clang IL (CIL) discussed, e.g., in https://llvm.org/devmtg/2019-04/slides/Keynote-ShpeismanLattner-MLIR.pdf, were to ever materialize as an MLIR dialect.

FYI During LLVM dev meeting 2020 a talk was presented: "CIL : Common MLIR Dialect for C/C++ and Fortran - Prashantha NR, Vinay Madhusudan, Ranjith Kumar, Srihari". But I think it is not open source for now?
Video link: https://www.youtube.com/watch?v=3gcw-8C9UbA&feature=youtu.be

**Comment by MattPD** [comment]
Thanks, indeed, "Clang Integration" is still under "Yet to see:" in https://llvm.org/devmtg/2020-09/slides/CIL_Common_MLIR_Abstraction.pdf

**Comment by xgupta** [comment]
Agree

**Pull request closed without merging**
