### PR TITLE
Software: Practice and Experience links & biblio.

### PR DESCRIPTION
**Pull request by FlashSheridan**
Add links for my Software: Practice and Experience compiler testing article and somewhat current bibliography.

### CODE REVIEW

**Comment by MattPD** [comment]
Thanks! Remember to add the author's (your) name.
I'm wondering if https://github.com/MattPD/cpplinks/blob/master/compilers.correctness.md#testing-readings wouldn't be a more precise section?

**Comment by FlashSheridan** [comment]
Excellent points; fixed my uncharacteristic modesty.  Will defer to your opinion on which section it belongs in.

**Comment by MattPD** [comment]
OK, thanks! :-) I think testing section may be better, should be ready to merge after moving.

**Comment by MattPD** [comment]
Added to testing section in commit df85d4d (https://github.com/MattPD/cpplinks/commit/df85d4dcd31539019e83cc909c7ad387502333fb); thanks!

**Pull request closed without merging**
